spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: myuser
    password: secret
management:
  health:
    db:
      enabled: false
  endpoint:
    health:
      probes:
        enabled: true
